account/urls.py
from django.urls import path

from . import views


app_name = 'auth'
urlpatterns = [
    path('signup', views.register, name='register'),
    path('login', views.auth_login, name='login'),
    path('logout', views.auth_logout, name='logout'),
]

chat/urls.py
from django.urls import path

from . import views


app_name='chat'
urlpatterns = [
    path('', views.chatFriendList, name='home'),
    path('friends', views.acceptedFriends, name='friends'),
    path('follow/request', views.followRequest, name='follow-req'),
    path('<str:friend_username>', views.chatWithFriend, name='chat_friend'),
    path('friend/<str:friend>/add', views.addNewFriends, name='add-friends'),
    path('friend/<str:friend>/accept', views.acceptFriendRequest, name='accept-friend-request'),
    path('friend/<str:friend>/remove', views.removeFriend, name='remove-friend'),
    path('message/unread', views.getNoUnreads, name='unreads'),
    path('friends/no', views.getNoFriends, name='no_friends'),
    path('groups/no', views.getNoGroups, name='no_groups'),
]

konnet/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic.base import RedirectView


from account import views


urlpatterns = [
    path("favivon.ico", RedirectView.as_view(url="blank_profile_pics.png")),
    path('__reload__/', include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
    path('auth/', include('account.urls')),
    path('', include('post.urls')),
]

handler404 = 'account.views.page_not_found'

handler500 = 'account.views.server_error'


# import time
# import threading

# def test():
#     while True:
#         time.sleep(10)
#         print("hello world")
    
# t1 = threading.Thread(target=test)
# t1.start()

templates/auth-old/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %} 
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Konnet</title>
  <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
  <header>
    <div id="auth">
      {% if user.is_authenticated %} 

      {% else %} 

      {% endif %} 
    </div>
  </header>
  <div id="container">
    
    <main>
      {% main block %} 
      {% endblock %} 
    </main>
    
  </div>
</body>
</html>

templates/auth-old/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %} 
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Authentication</title>
  <link rel="stylesheet" href="{% static 'auth/auth_style.css' %}">
  <style>
  </style>
</head>
<body>
  <header>
  </header>
  <div id="container">
    <main>
      {% for message in messages %} 
        <div id='alert'>{{ message }}</div>
      {% endfor %}
      <h1 id="login">Login</h1>
      <form action="{% url 'auth:login' %}" method="post">
        {% csrf_token %} 
        <div class="user-input">
          <label for="username">Username</label>
          <input type="text" id="username" name="username" placeholder="Username or Email" autocomplete="off" required>
        </div>

        <div class="user-input">
          <label for="password">Password</label>
          <input type="password" id="password" name="password" placeholder="Password" autocomplete="off" required>
        </div>

        <input id="submit" type="submit" value="Login">
      
        <div id="or-login"><a href="{% url 'auth:register' %}">Register</a></div>
      </form>
    </main>
  </div>
  <script>
    const alert_message = document.querySelector('#alert');
    setTimeout(() => {
      alert_message.style.display = 'none'
    }, 3000);
  </script>
</body>
</html>

templates/auth-old/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Authentication</title>
  <link rel="stylesheet" href="{% static 'auth/auth_style.css' %}">
</head>
<body>
  <header>
  </header>
  <div id="container">
    <main id="login-main">
      <h1>Register</h1>
      <form action="{% url 'auth:register' %}" method="post">
        {% csrf_token %}
        <div class="user-input">
          <label for="username">Username</label>
          <input type="text" id="username" name="username" autocomplete="off" placeholder="Username" required>
        </div>

        <div class="user-input">
          <label for="email">Email</label>
          <input type="email" id="email" name="email" autocomplete="off" placeholder="Email"required>
        </div>

        <div class="user-input">
          <label for="fname">Full name</label>
          <input type="text" id="fname" name="fname" autocomplete="off" placeholder="Full name" required>
        </div>

        <div class="user-input">
          <label for="password">Password</label>
          <input type="password" id="password" name="password" autocomplete="off" placeholder="Password" required>
        </div>

        <div class="user-input">
          <label for="verity-password">Verify password</label>
          <input type="password" id="verify-password" name="verify-password" autocomplete="off" placeholder="Verify password" required>
        </div>

        <div class="user-input">
          <label for="phone-no">Phone Number</label>
          <input type="text" id="phone-no" name="phone-no" autocomplete="off" placeholder="Phone number" required>
        </div>
        <input id="submit" type="submit" value="Register">
      
        <div id="or-login"><a href="{% url 'auth:login' %}">Login</a></div>
      </form>
    </main>
  </div>
</body>
</html>