chat/urls.py
from django.urls import path

from . import views


app_name='chat'
urlpatterns = [
    path('', views.chatFriendList, name='home'),
    path('friends', views.acceptedFriends, name='friends'),
    path('follow/request', views.followRequest, name='follow-req'),
    path('<str:friend_username>', views.chatWithFriend, name='chat_friend'),
    path('friend/<str:friend>/add', views.addNewFriends, name='add-friends'),
    path('friend/<str:friend>/accept', views.acceptFriendRequest, name='accept-friend-request'),
    path('friend/<str:friend>/remove', views.removeFriend, name='remove-friend'),
    path('message/unread', views.getNoUnreads, name='unreads'),
    path('friends/no', views.getNoFriends, name='no_friends'),
    path('groups/no', views.getNoGroups, name='no_groups'),
]

konnet/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic.base import RedirectView


from account import views


urlpatterns = [
    path("favivon.ico", RedirectView.as_view(url="blank_profile_pics.png")),
    path('__reload__/', include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
    path('auth/', include('account.urls')),
    path('', include('post.urls')),
]

handler404 = 'account.views.page_not_found'

handler500 = 'account.views.server_error'


# import time
# import threading

# def test():
#     while True:
#         time.sleep(10)
#         print("hello world")
    
# t1 = threading.Thread(target=test)
# t1.start()

post/urls.py
from django.urls import path

from . import views


app_name = 'post'
urlpatterns = [
    path('', views.home, name='home'),
    path('update', views.updatePost, name='update-post'),
    path('profile', views.profile, name='profile'),
    path('profile/<str:user>', views.friend_profile, name= "friend-profile"),
]

templates/friends/chat_friends.html
{% extends 'base/base.html' %}

{% block custom-style %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'friends/friend_list_style.css' %}">
{% endblock %}

{% block title %}
  Friends
{% endblock %}

{% block main %}
<form action="#" id="friend-search">
  <input type="text">
  <input type="submit" value="search">
</form>

<div id="friend-list">
  <h2>Friends</h2>
  {% for friend in friends %}
  <div class="friend">
    <div class="friend-profile">
      <a href="" class="avatar-link">
        <img src="{% static 'blank-profile-pics.png' %}" alt="blank profile pics">
      </a>
      <a href="{% url 'chat:chat_friend' friend %}" class="profile-link">
        <span class="profile-name">{{ friend.first_name }} {{ friend.user.last_name }}</span>
        <span class="profile-username">@{{ friend.username }}</span>
      </a>
    </div>
    {% include 'includes/follow.html' %}
  </div>
  {% endfor %}
  
</div>
{% endblock %}

<!-- <!DOCTYPE html>
<html lang="en">
<head>
  {% load static %} 
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="{% static 'style_friend_list.css' %}">
  <script>
    document.addEventListener('DOMContentLoaded', () => {
      const burger_bttn = document.getElementById('burger-button');
      burger_bttn.addEventListener('click', () => {
        const nav = document.querySelector('nav');
        
        if (getComputedStyle(nav).display == 'block') {
          nav.style.display = 'none';
        } else {
          nav.style.display = 'block';
        }
      });

      // console.log(document);
      
      // document.querySelector('ht').addEventListener('click', () => {
      //   const nav = document.querySelector('nav');
      //   if (getComputedStyle(nav).display == 'block') {
      //     nav.style.display = 'none';
      //   }
      // })
    })


  </script>
</head>
<body>
  <div id="body-container">
    <header>
      <div id="left-header">
        <button id="burger-button">
          <div id="burger"></div>
        </button>
        <div id="app-name">
          <a href="">Konnet</a>
        </div>
      </div>
      <div id="auth">
        <a href="">login</a>
      </div>
    </header>
    
    <div id="container">
      <nav>
        <div class="nav-item">
          <a href="#">
            <span>Chat</span><span class="notify-no">99</span>
          </a>
        </div>

        <div class="nav-item">
          <a href="">
            <span>Posts</span><span class="notify-no">99</span>
          </a>
        </div>

        <div class="nav-item">
          <a href="">
            <span>Friends</span><span class="notify-no">99</span>
          </a>
        </div>

        <div class="nav-item">
          <a href="">
            <span>Friend Requests</span><span class="notify-no">99</span>
          </a>
        </div>
      </nav>
  
      <main>
        <form action="#" id="friend-search">
          <input type="text">
          <input type="submit" value="search">
        </form>

        <div id="friend-list">
          <div class="friend">
            <div class="friend-profile">
              <a href="" class="avatar-link">
                <img src="./blank-profile-pics.png" alt="blank profile pics">
              </a>
              <a href="" class="profile-link">
                <span class="profile-name">David</span>
                <span class="profile-username">@davidjoy</span>
              </a>
            </div>
            <button class="profile-shortcut">
              <div></div>
            </button>
          </div>

          <div class="friend">
            <div class="friend-profile">
              <a href="" class="avatar-link">
                <img src="./blank-profile-pics.png" alt="blank profile pics">
              </a>
              <a href="" class="profile-link">
                <span class="profile-name">David</span>
                <span class="profile-username">@davidjoy</span>
              </a>
            </div>
            <button class="profile-shortcut">
              <div></div>
            </button>
          </div>

          <div class="friend">
            <div class="friend-profile">
              <a href="" class="avatar-link">
                <img src="./blank-profile-pics.png" alt="blank profile pics">
              </a>
              <a href="" class="profile-link">
                <span class="profile-name">David</span>
                <span class="profile-username">@davidjoy</span>
              </a>
            </div>
            <button class="profile-shortcut">
              <div></div>
            </button>
          </div>

          <div class="friend">
            <div class="friend-profile">
              <a href="" class="avatar-link">
                <img src="./blank-profile-pics.png" alt="blank profile pics">
              </a>
              <a href="" class="profile-link">
                <span class="profile-name">David</span>
                <span class="profile-username">@davidjoy</span>
              </a>
            </div>
            <button class="profile-shortcut">
              <div></div>
            </button>
          </div>

          <div class="friend">
            <div class="friend-profile">
              <a href="" class="avatar-link">
                <img src="./blank-profile-pics.png" alt="blank profile pics">
              </a>
              <a href="" class="profile-link">
                <span class="profile-name">David</span>
                <span class="profile-username">@davidjoy</span>
              </a>
            </div>
            <button class="profile-shortcut">
              <div></div>
            </button>
          </div>

          <div class="friend">
            <div class="friend-profile">
              <a href="" class="avatar-link">
                <img src="./blank-profile-pics.png" alt="blank profile pics">
              </a>
              <a href="" class="profile-link">
                <span class="profile-name">David</span>
                <span class="profile-username">@davidjoy</span>
              </a>
            </div>
            <button class="profile-shortcut">
              <div></div>
            </button>
          </div>

          <div class="friend">
            <div class="friend-profile">
              <a href="" class="avatar-link">
                <img src="./blank-profile-pics.png" alt="blank profile pics">
              </a>
              <a href="" class="profile-link">
                <span class="profile-name">David</span>
                <span class="profile-username">@davidjoy</span>
              </a>
            </div>
            <button class="profile-shortcut">
              <div></div>
            </button>
          </div>

          <div class="friend">
            <div class="friend-profile">
              <a href="" class="avatar-link">
                <img src="./blank-profile-pics.png" alt="blank profile pics">
              </a>
              <a href="" class="profile-link">
                <span class="profile-name">David</span>
                <span class="profile-username">@davidjoy</span>
              </a>
            </div>
            <button class="profile-shortcut">
              <div></div>
            </button>
          </div>

          <div class="friend">
            <div class="friend-profile">
              <a href="" class="avatar-link">
                <img src="./blank-profile-pics.png" alt="blank profile pics">
              </a>
              <a href="" class="profile-link">
                <span class="profile-name">Jason</span>
                <span class="profile-username">@Jason</span>
              </a>
            </div>
            <button class="profile-shortcut">
              <div></div>
            </button>
          </div>
        </div>
      </main>
  
      <aside id="right">
      </aside>
    </div>
  </div>
</body>
</html> -->

templates/friends/chatted_friends.html
{% extends 'base/base.html' %}

{% block custom-style %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'friends/friend_list_style.css' %}">
{% endblock %}

{% block title %}
  Friends
{% endblock %}

{% block main %}
<form action="#" id="friend-search">
  <input type="text">
  <input type="submit" value="search">
</form>

<div id="friend-list">
  <h2>Chats</h2>

  {% for friend in friends %}
  <div class="friend">
    <div class="friend-profile">
      <a href="" class="avatar-link">
        <img src="{% static 'blank-profile-pics.png' %}" alt="blank profile pics">
      </a>
      <a href="{% url 'chat:chat_friend' friend %}" class="profile-link">
        <span class="profile-name">{{ friend.first_name }} {{ friend.last_name }}</span>
        <span class="profile-username">@{{ friend.username }}</span>
      </a>
    </div>
    {% include 'includes/frnd-menu-bttn.html' %}
  </div>
  {% endfor %}
  
</div>
{% endblock %}

<!-- <!DOCTYPE html>
<html lang="en">
<head>
  {% load static %} 
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="{% static 'style_friend_list.css' %}">
  <script>
    document.addEventListener('DOMContentLoaded', () => {
      const burger_bttn = document.getElementById('burger-button');
      burger_bttn.addEventListener('click', () => {
        const nav = document.querySelector('nav');
        
        if (getComputedStyle(nav).display == 'block') {
          nav.style.display = 'none';
        } else {
          nav.style.display = 'block';
        }
      });

      // console.log(document);
      
      // document.querySelector('ht').addEventListener('click', () => {
      //   const nav = document.querySelector('nav');
      //   if (getComputedStyle(nav).display == 'block') {
      //     nav.style.display = 'none';
      //   }
      // })
    })


  </script>
</head>
<body>
  <div id="body-container">
    <header>
      <div id="left-header">
        <button id="burger-button">
          <div id="burger"></div>
        </button>
        <div id="app-name">
          <a href="">Konnet</a>
        </div>
      </div>
      <div id="auth">
        <a href="">login</a>
      </div>
    </header>
    
    <div id="container">
      <nav>
        <div class="nav-item">
          <a href="#">
            <span>Chat</span><span class="notify-no">99</span>
          </a>
        </div>

        <div class="nav-item">
          <a href="">
            <span>Posts</span><span class="notify-no">99</span>
          </a>
        </div>

        <div class="nav-item">
          <a href="">
            <span>Friends</span><span class="notify-no">99</span>
          </a>
        </div>

        <div class="nav-item">
          <a href="">
            <span>Friend Requests</span><span class="notify-no">99</span>
          </a>
        </div>
      </nav>
  
      <main>
        <form action="#" id="friend-search">
          <input type="text">
          <input type="submit" value="search">
        </form>

        <div id="friend-list">
          <div class="friend">
            <div class="friend-profile">
              <a href="" class="avatar-link">
                <img src="./blank-profile-pics.png" alt="blank profile pics">
              </a>
              <a href="" class="profile-link">
                <span class="profile-name">David</span>
                <span class="profile-username">@davidjoy</span>
              </a>
            </div>
            <button class="profile-shortcut">
              <div></div>
            </button>
          </div>

          <div class="friend">
            <div class="friend-profile">
              <a href="" class="avatar-link">
                <img src="./blank-profile-pics.png" alt="blank profile pics">
              </a>
              <a href="" class="profile-link">
                <span class="profile-name">David</span>
                <span class="profile-username">@davidjoy</span>
              </a>
            </div>
            <button class="profile-shortcut">
              <div></div>
            </button>
          </div>

          <div class="friend">
            <div class="friend-profile">
              <a href="" class="avatar-link">
                <img src="./blank-profile-pics.png" alt="blank profile pics">
              </a>
              <a href="" class="profile-link">
                <span class="profile-name">David</span>
                <span class="profile-username">@davidjoy</span>
              </a>
            </div>
            <button class="profile-shortcut">
              <div></div>
            </button>
          </div>

          <div class="friend">
            <div class="friend-profile">
              <a href="" class="avatar-link">
                <img src="./blank-profile-pics.png" alt="blank profile pics">
              </a>
              <a href="" class="profile-link">
                <span class="profile-name">David</span>
                <span class="profile-username">@davidjoy</span>
              </a>
            </div>
            <button class="profile-shortcut">
              <div></div>
            </button>
          </div>

          <div class="friend">
            <div class="friend-profile">
              <a href="" class="avatar-link">
                <img src="./blank-profile-pics.png" alt="blank profile pics">
              </a>
              <a href="" class="profile-link">
                <span class="profile-name">David</span>
                <span class="profile-username">@davidjoy</span>
              </a>
            </div>
            <button class="profile-shortcut">
              <div></div>
            </button>
          </div>

          <div class="friend">
            <div class="friend-profile">
              <a href="" class="avatar-link">
                <img src="./blank-profile-pics.png" alt="blank profile pics">
              </a>
              <a href="" class="profile-link">
                <span class="profile-name">David</span>
                <span class="profile-username">@davidjoy</span>
              </a>
            </div>
            <button class="profile-shortcut">
              <div></div>
            </button>
          </div>

          <div class="friend">
            <div class="friend-profile">
              <a href="" class="avatar-link">
                <img src="./blank-profile-pics.png" alt="blank profile pics">
              </a>
              <a href="" class="profile-link">
                <span class="profile-name">David</span>
                <span class="profile-username">@davidjoy</span>
              </a>
            </div>
            <button class="profile-shortcut">
              <div></div>
            </button>
          </div>

          <div class="friend">
            <div class="friend-profile">
              <a href="" class="avatar-link">
                <img src="./blank-profile-pics.png" alt="blank profile pics">
              </a>
              <a href="" class="profile-link">
                <span class="profile-name">David</span>
                <span class="profile-username">@davidjoy</span>
              </a>
            </div>
            <button class="profile-shortcut">
              <div></div>
            </button>
          </div>

          <div class="friend">
            <div class="friend-profile">
              <a href="" class="avatar-link">
                <img src="./blank-profile-pics.png" alt="blank profile pics">
              </a>
              <a href="" class="profile-link">
                <span class="profile-name">Jason</span>
                <span class="profile-username">@Jason</span>
              </a>
            </div>
            <button class="profile-shortcut">
              <div></div>
            </button>
          </div>
        </div>
      </main>
  
      <aside id="right">
      </aside>
    </div>
  </div>
</body>
</html> -->

templates/friends/friend_req.html
{% extends 'base/base.html' %}

{% load static %}

{% block custom-style %}
<link rel="stylesheet" href="{% static 'friends/friend_list_style.css' %}?{% now 'U' %}">
{% endblock %}

{% block title %}
  Friend Requests
{% endblock %}


{% block main %}
<form action="#" id="friend-search">
  <input type="text">
  <input type="submit" value="search">
</form>

<div id="friend-list">
  <h2>Friend Requests</h2>

  {% for friend in friend_request %}
  <div class="friend">
    <div class="friend-profile">
      <a href="{% url 'post:friend-profile' friend.username %}" class="avatar-link">
        <img src="{% static 'blank-profile-pics.png' %}" alt="blank profile pics">
      </a>
      <a href="{% url 'chat:chat_friend' friend.username %}" class="profile-link">
        <span class="profile-name">{{ friend.first_name }} {{ friend.user.last_name }}</span>
        <span class="profile-username">@{{ friend.username }}</span>
      </a>
    </div>
    <a href="{% url 'chat:accept-friend-request' friend.username %}">
      {% include 'includes/accept.html' %}
    </a>
  </div>
  {% endfor %}
  
</div>
{% endblock %}

templates/friends/list_friends.html
{% extends 'base/base.html' %}

{% block custom-style %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'friends/friend_list_style.css' %}">
{% endblock %}


{% block title %}
  Friends
{% endblock %}


{% block main %}
<style>
  /* .friend {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: -moz-box;
    justify-content: space-between;
  }
  .friend-profile {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: -moz-box;
    gap: 2rem;
  }
  .profile-link { */
    /* align-self: center; */
    /* font-size: 1.8rem; */
  /* } */
</style>
<form action="#" id="friend-search">
  <input type="text">
  <input type="submit" value="search">
</form>

<div id="friend-list">
  <h2>Friends</h2>
  {% for friend_profile in friends %}
  <div class="friend">
    <div class="friend-profile">
      <a href="{% url 'post:friend-profile' friend_profile.other_user.username %}" class="avatar-link">
        <img src="{% static 'blank-profile-pics.png' %}" alt="blank profile pics">
      </a>
      <a href="{% url 'chat:chat_friend' friend_profile.other_user.username %}" class="profile-link">
        <span class="profile-name">{{ friend_profile.other_user.first_name }} {{ friend_profile.other_user.last_name }}</span>
        <span class="profile-username">@{{ friend_profile.other_user.username }}</span>
      </a>
    </div>
    {% include 'includes/frnd-menu-bttn.html' %}
  </div>
  {% endfor %}

  <h2>Recommended Friends</h2>

  {% for friend in recommended_friends %} 
  <div class="friend">
    <div class="friend-profile">
      <a href="{% url 'post:friend-profile' friend.username %}" class="avatar-link">
        <img src="{% static 'blank-profile-pics.png' %}" alt="blank profile pics">
      </a>
      <a href="{% url 'chat:chat_friend' friend.username %}" class="profile-link">
        <span class="profile-name">{{ friend.first_name }} {{ friend.last_name }}</span>
        <span class="profile-username">@{{ friend.username }}</span>
      </a>
    </div>
    <a href="{% url 'chat:add-friends' friend.username %}">
      {% include 'includes/follow.html' %}
    </a>
  </div>
  {% endfor %}
</div>
{% endblock %}

<!-- <!DOCTYPE html>
<html lang="en">
<head>
  {% load static %} 
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="{% static 'style_friend_list.css' %}">
  <script>
    document.addEventListener('DOMContentLoaded', () => {
      const burger_bttn = document.getElementById('burger-button');
      burger_bttn.addEventListener('click', () => {
        const nav = document.querySelector('nav');
        
        if (getComputedStyle(nav).display == 'block') {
          nav.style.display = 'none';
        } else {
          nav.style.display = 'block';
        }
      });

      // console.log(document);
      
      // document.querySelector('ht').addEventListener('click', () => {
      //   const nav = document.querySelector('nav');
      //   if (getComputedStyle(nav).display == 'block') {
      //     nav.style.display = 'none';
      //   }
      // })
    })


  </script>
</head>
<body>
  <div id="body-container">
    <header>
      <div id="left-header">
        <button id="burger-button">
          <div id="burger"></div>
        </button>
        <div id="app-name">
          <a href="">Konnet</a>
        </div>
      </div>
      <div id="auth">
        <a href="">login</a>
      </div>
    </header>
    
    <div id="container">
      <nav>
        <div class="nav-item">
          <a href="#">
            <span>Chat</span><span class="notify-no">99</span>
          </a>
        </div>

        <div class="nav-item">
          <a href="">
            <span>Posts</span><span class="notify-no">99</span>
          </a>
        </div>

        <div class="nav-item">
          <a href="">
            <span>Friends</span><span class="notify-no">99</span>
          </a>
        </div>

        <div class="nav-item">
          <a href="">
            <span>Friend Requests</span><span class="notify-no">99</span>
          </a>
        </div>
      </nav>
  
      <main>
        <form action="#" id="friend-search">
          <input type="text">
          <input type="submit" value="search">
        </form>

        <div id="friend-list">
          <div class="friend">
            <div class="friend-profile">
              <a href="" class="avatar-link">
                <img src="./blank-profile-pics.png" alt="blank profile pics">
              </a>
              <a href="" class="profile-link">
                <span class="profile-name">David</span>
                <span class="profile-username">@davidjoy</span>
              </a>
            </div>
            <button class="profile-shortcut">
              <div></div>
            </button>
          </div>

          <div class="friend">
            <div class="friend-profile">
              <a href="" class="avatar-link">
                <img src="./blank-profile-pics.png" alt="blank profile pics">
              </a>
              <a href="" class="profile-link">
                <span class="profile-name">David</span>
                <span class="profile-username">@davidjoy</span>
              </a>
            </div>
            <button class="profile-shortcut">
              <div></div>
            </button>
          </div>

          <div class="friend">
            <div class="friend-profile">
              <a href="" class="avatar-link">
                <img src="./blank-profile-pics.png" alt="blank profile pics">
              </a>
              <a href="" class="profile-link">
                <span class="profile-name">David</span>
                <span class="profile-username">@davidjoy</span>
              </a>
            </div>
            <button class="profile-shortcut">
              <div></div>
            </button>
          </div>

          <div class="friend">
            <div class="friend-profile">
              <a href="" class="avatar-link">
                <img src="./blank-profile-pics.png" alt="blank profile pics">
              </a>
              <a href="" class="profile-link">
                <span class="profile-name">David</span>
                <span class="profile-username">@davidjoy</span>
              </a>
            </div>
            <button class="profile-shortcut">
              <div></div>
            </button>
          </div>

          <div class="friend">
            <div class="friend-profile">
              <a href="" class="avatar-link">
                <img src="./blank-profile-pics.png" alt="blank profile pics">
              </a>
              <a href="" class="profile-link">
                <span class="profile-name">David</span>
                <span class="profile-username">@davidjoy</span>
              </a>
            </div>
            <button class="profile-shortcut">
              <div></div>
            </button>
          </div>

          <div class="friend">
            <div class="friend-profile">
              <a href="" class="avatar-link">
                <img src="./blank-profile-pics.png" alt="blank profile pics">
              </a>
              <a href="" class="profile-link">
                <span class="profile-name">David</span>
                <span class="profile-username">@davidjoy</span>
              </a>
            </div>
            <button class="profile-shortcut">
              <div></div>
            </button>
          </div>

          <div class="friend">
            <div class="friend-profile">
              <a href="" class="avatar-link">
                <img src="./blank-profile-pics.png" alt="blank profile pics">
              </a>
              <a href="" class="profile-link">
                <span class="profile-name">David</span>
                <span class="profile-username">@davidjoy</span>
              </a>
            </div>
            <button class="profile-shortcut">
              <div></div>
            </button>
          </div>

          <div class="friend">
            <div class="friend-profile">
              <a href="" class="avatar-link">
                <img src="./blank-profile-pics.png" alt="blank profile pics">
              </a>
              <a href="" class="profile-link">
                <span class="profile-name">David</span>
                <span class="profile-username">@davidjoy</span>
              </a>
            </div>
            <button class="profile-shortcut">
              <div></div>
            </button>
          </div>

          <div class="friend">
            <div class="friend-profile">
              <a href="" class="avatar-link">
                <img src="./blank-profile-pics.png" alt="blank profile pics">
              </a>
              <a href="" class="profile-link">
                <span class="profile-name">Jason</span>
                <span class="profile-username">@Jason</span>
              </a>
            </div>
            <button class="profile-shortcut">
              <div></div>
            </button>
          </div>
        </div>
      </main>
  
      <aside id="right">
      </aside>
    </div>
  </div>
</body>
</html> -->