chat/urls.py
from django.urls import path

from . import views


app_name='chat'
urlpatterns = [
    path('', views.chatFriendList, name='home'),
    path('friends', views.acceptedFriends, name='friends'),
    path('follow/request', views.followRequest, name='follow-req'),
    path('<str:friend_username>', views.chatWithFriend, name='chat_friend'),
    path('friend/<str:friend>/add', views.addNewFriends, name='add-friends'),
    path('friend/<str:friend>/accept', views.acceptFriendRequest, name='accept-friend-request'),
    path('friend/<str:friend>/remove', views.removeFriend, name='remove-friend'),
    path('message/unread', views.getNoUnreads, name='unreads'),
    path('friends/no', views.getNoFriends, name='no_friends'),
    path('groups/no', views.getNoGroups, name='no_groups'),
]

konnet/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic.base import RedirectView


from account import views


urlpatterns = [
    path("favivon.ico", RedirectView.as_view(url="blank_profile_pics.png")),
    path('__reload__/', include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
    path('auth/', include('account.urls')),
    path('', include('post.urls')),
]

handler404 = 'account.views.page_not_found'

handler500 = 'account.views.server_error'


# import time
# import threading

# def test():
#     while True:
#         time.sleep(10)
#         print("hello world")
    
# t1 = threading.Thread(target=test)
# t1.start()

chat/models.py
from django.db import models
from django.conf import settings

from account.models import Profile, Friendship
from django.contrib.auth.models import User


# class Friend(models.Model):
#     user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     friend_list = models.ManyToManyField(Profile, blank=True)

#     class Meta:
#         verbose_name='Friend'
#         verbose_name_plural = 'Friends'

#     def __str__(self):
#         return self.user.username
    
#     @classmethod
#     def list_friends(cls, user):
#         return cls.objects.get(user=user).friend_list.all()
    
#     @classmethod
#     def create_friend(cls, user):
#         cls.objects.create(user=user).save()

#     @classmethod
#     def delete_friend(cls, user):
#         try:
#             friend = cls.objects.get(user=user)
#             friend.delete()
#         except Exception:
#             pass
    
#     @classmethod
#     def send_message(cls, sent_from, sent_to, text):
#         sender = cls.objects.get(user=sent_from)
#         to = sender.friend_list.get(user=sent_to)
#         message = Message.objects.create(sender=sender.user, text=text, receiver=to)
#         message.save()

#     @classmethod
#     def add_friend(cls, user, new_friend):
#         user = cls.objects.get(user=user)
#         if new_friend.user != user:
#             user.friend_list.add(new_friend)

class ChatGroup(models.Model):
    status = (
        ('member', 'Member'),
        ('admin', 'Admin')
    )
    creator = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='Creator')
    name = models.CharField(max_length=20)
    member = models.ManyToManyField(Profile, blank=True, related_name='Member', through='Membership', through_fields=('chat_group', 'profile'))
    
    class Meta:
        verbose_name = 'Group'
        verbose_name_plural = 'Groups'

    def __str__(self):
        return self.name
    
    @classmethod
    def list_groups(cls):
        return cls.objects.all()

    @classmethod
    def create_group(cls, creator, name):
        new_group = cls.objects.create(creator=creator, name=name)
        new_group.save()
        new_group.member.add(creator)
        #-----------------what i needed to update-----------------
        # chat_group = ChatGroup.objects.get(creator)
        # -------------------------

    #-------correction needed here------------
    #add members to groups
    @classmethod
    def add_group_member(cls, group_name, new_member):
        chat_group = cls.objects.get(name=group_name)
        user_profile = Profile.objects.get(username=settings.AUTH_USER_MODEL)
        auth_user_in_group = chat_group.membership_set.get(profile=user_profile)
        if auth_user_in_group.through.rank == 'Admin':
            chat_group.member.add(new_member)
        else:
            raise PermissionError("Non-admin not allowed to add member")
        #----------------------------


    @classmethod
    def delete_group(cls, name):
        group = cls.objects.get(name=name)
        group.delete()

    def remove_member(self, profile):
        auth_user = self.member.get(user=settings.AUTH_USER_MODEL)

        if auth_user.through.status == 'Admin':
            member = self.member.get(user=profile)
            member.remove()
        else:
            raise PermissionError("Non-admin not allowed remove members")
        
    @staticmethod
    def send_message(sender, chat_group, msg):
        
        GroupMessage.objects.create(group=chat_group, text=msg).save()

class Membership(models.Model):

    status = (
        ('admin', 'Admin'),
        ('member', 'Member')
    )

    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    chat_group = models.ForeignKey(ChatGroup, on_delete=models.CASCADE)
    status = models.CharField(
        max_length=8,
        choices=status,
        default='member'
        )
    added_when = models.DateTimeField(auto_now=True)
        
class GroupMessage(models.Model):
    group = models.ForeignKey(ChatGroup, on_delete=models.CASCADE)
    text = models.TextField()
    sent_when = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Message'
        verbose_name_plural = 'Messages'

    def __str__(self):
        return self.text[:10]
    
class Message(models.Model):
    sender = models.ForeignKey(Profile, related_name="Sender", on_delete=models.CASCADE)
    text = models.TextField()
    sent_at = models.DateTimeField(auto_now=True)
    read = models.BooleanField(default=False)
    receiver = models.ForeignKey(Profile, related_name="Receiver", on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Message'
        verbose_name_plural = 'Messages'

    def __str__(self):
        return self.text[:10]
    
    @classmethod
    def send_message(cls, sender, msg, receiver):
        friends = sender.getAcceptedFriends()
        receiver_friendship = Friendship.objects.get(user=sender, other_user=receiver)
        if receiver_friendship in friends:
            msg = cls.objects.create(sender=sender, text=msg, receiver=receiver)
            msg.save()
        else:
            raise PermissionError("You are not allowed to send message to a user not on your list.")

    def message_read(self):
        self.read = True
    

chat/views.py
import json
from django.db.models import Q
from django.urls import reverse
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required

from account.models import Profile, Friendship
from chat.models import ChatGroup, Message

@login_required()
def chatFriendList(request):
    """
    List friends chatted with:
    from latest to the oldest
    """
    username = request.user.username
    user_profile= Profile.objects.get(username=username)

    sender_receiver_ids = Message.objects.filter(
        Q(sender=user_profile) |
        Q(receiver=user_profile)
    ).values_list('sender', 'receiver')

    # chat id filtering out the auth user id
    chats = []


    for ids in sender_receiver_ids:
        for chat_id in ids:
            if chat_id != user_profile.id:
                chats.append(Profile.objects.get(id=chat_id))

    chats = set(chats) # remove duplicates with set

    # get list messages latest where the chats profile appears as the sender
    # or the receiver and then sort using sent_at(time) as the key
    
    latest_messages = [
        Message.objects.filter(
            (Q(sender=user_profile)&
            Q(receiver=friend_profile)) |
            (Q(sender=friend_profile)&
            Q(receiver=user_profile)
        )).latest('sent_at')

        for friend_profile in chats
    ]  # Get message latest where friend_profile is either the sender or the receiver

    chatted_friends = sorted(latest_messages, key=lambda k: k.sent_at, reverse=True)

    friends = []

    for msg in chatted_friends:
        if msg.sender.username == request.user.username:
            friends.append(msg.receiver)

        elif msg.receiver.username == request.user.username:
            friends.append(msg.sender)
    
    # chatted_friends = [
    #     Profile.objects.get(id=id[0])
    #     for id in Message.objects.filter(sender=sender).values_list('receiver').distinct()
    # ]

    context = {
        # 'friends': chatted_friends
        'friends': friends
    }

    return render(request, 'friends/chatted_friends.html', context)

@login_required
def chatWithFriend(request, friend_username):
    """
    Chat interface to chat friends
    """
    user = request.user
    user_profile = Profile.objects.get(username=user.username)
    friend_profile = get_object_or_404(Profile, username=friend_username)

    messages = Message.objects.filter(
        (Q(sender=user_profile)&
        Q(receiver=friend_profile)) |
        (Q(sender=friend_profile)&
        Q(receiver=user_profile))
    )
    if request.method == 'POST':
        data = json.load(request)
        print(data)
        text_msg = data["msg"]
        Message.send_message(user_profile, text_msg, friend_profile)
        # Message.send_message(user_profile, text, friend_profile)
        return HttpResponse({200: "success"})

    context = {
        'friend_profile': friend_profile,
        'messages': messages.order_by('sent_at')
    }

    return render(request, 'chats/home.html', context)

@login_required
def receiveChat(request, username):
    ...

@login_required
def acceptedFriends(request):
    """
    List friends. People who are already friends
    """
    username = request.user.username

    user_profile = Profile.objects.get(username=username)
    friend_list = user_profile.getAcceptedFriends()

    # Get all the profile who are neither on my friend list
    # nor the authenticated user
    profiles = Profile.objects.exclude(username=username)
    recommended_friends = []
    friend_profiles = [i.other_user for i in friend_list]
    for profile in profiles:
        if profile not in friend_profiles :
            recommended_friends.append(profile)

    context = {
        'friends': friend_list,
        'recommended_friends': recommended_friends
    }

    return render(request, 'friends/list_friends.html', context)

def listFriends(request):
    user_profile = Profile.objects.get(username=request.user.username)
    friend_list = user_profile.friends.all()
    context = {
        'friends': friend_list
    }

    return render(request, 'friends/list_friends.html', context)
    

def getNoUnreads(request):
    user_profile = Profile.obects.get(username=request.user.username)

    unread_messages = Message.objects.filter(
        receiver=user_profile.profile, read=False).count()
    
    unread = {'unread_messages': unread_messages}

    return JsonResponse(unread)

def getNoFriends(request):
    authenticated = request.user
    user_profile = Profile.objects.get(username=authenticated)
    
    no_of_friends = user_profile.friends.all().count()
    return JsonResponse({"no_of_friends": no_of_friends})

def getNoGroups(request):
    authenticated = request.user
    user_profile = Profile.objects.get(username=authenticated)
    user_group_chat = user_profile.chatgroup_set.all()
    no_chatgroup = user_group_chat.count()

    return JsonResponse({"no_chatgroup": no_chatgroup})
    

def addNewFriends(request, friend):
    user_profile = Profile.objects.get(username=request.user.username)
    friend_profile = Profile.objects.get(username=friend)
    user_profile.addFriend(friend_profile)
    return redirect('/')

def acceptFriendRequest(request, friend):
    user_profile = Profile.objects.get(username=request.user.username)
    friend_profile = Profile.objects.get(username=friend)
    user_profile.acceptRequest(friend_profile)
    return redirect('/')

def removeFriend(request, friend):
    user_profile = Profile.objects.get(username=request.user.username)
    friend_profile = Profile.objects.get(username=friend)
    user_profile.removeFriend(friend_profile)

def getGroups(request):
    groups = ChatGroup.list_groups()

    context = {
        'groups': groups
    }

    return JsonResponse(context)

@login_required
def followRequest(request):
    user_profile = Profile.objects.get(username=request.user.username)
    get_all_friend_req = user_profile.getFriendRequests()
    
    context = {
        'friend_request': get_all_friend_req
    }

    return render(request, 'friends/friend_req.html', context)

templates/chats/home.html
{% extends 'base/base.html' %} 
<!-- <!DOCTYPE html>
<html lang="en">
<head>
  {% load static %} 
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <script>
    document.addEventListener('DOMContentLoaded', () => {
      const burger_bttn = document.getElementById('burger-button');
      burger_bttn.addEventListener('click', () => {
        const nav = document.querySelector('nav');
        
        if (getComputedStyle(nav).display == 'block') {
          nav.style.display = 'none';
        } else {
          nav.style.display = 'block';
        }
      });

      const chat_message = document.querySelector('#chat-message');
      // scroll to the bottom of the chat messages
      chat_message.scrollTo(0, chat_message.scrollHeight);

      console.log(document);
      
      // document.querySelector('ht').addEventListener('click', () => {
      //   const nav = document.querySelector('nav');
      //   if (getComputedStyle(nav).display == 'block') {
      //     nav.style.display = 'none';
      //   }
      // // })

      // const main = document.querySelector('main');
      // let chat_form = document.querySelector('#chat-form');
      // chat_form.style.width = getComputedStyle(main).width;;
    })


  </script>
</head>
<body>
  <div id="body-container">
    <header>
      <div id="left-header">
        <button id="burger-button">
          <div id="burger"></div>
        </button>
        <div id="app-name">
          <a href="">Konnet</a>
        </div>
      </div>
      <div id="auth">
        <a href="">login</a>
      </div>
    </header>
    
    <div id="container">
      <nav>
        <div class="nav-item">
          <a href="#">
            <span>Chat</span><span class="notify-no">99</span>
          </a>
        </div>

        <div class="nav-item">
          <a href="">
            <span>Posts</span><span class="notify-no">99</span>
          </a>
        </div>

        <div class="nav-item">
          <a href="{% url 'chat:friends' %}">
            <span>Friends</span><span class="notify-no">99</span>
          </a>
        </div>

        <div class="nav-item">
          <a href="">
            <span>Friend Requests</span><span class="notify-no">99</span>
          </a>
        </div>
      </nav>
  
      <main>
        <div id="profile-info">
          <div id="profile">
            <img src="./blank-profile-pics.png" alt="blank pics">
            <div id="username">David</div>
          </div>

          <button id="burger-button">
            <div id="burger"></div>
          </button>
        </div>

        <div id="chat-message">
          <div class="sender">Hello world</div>
          <div class="receiver">I'm happy you get back to me</div>
          <div class="sender">Hello world</div>
          <div class="receiver">I'm happy you get back to me</div>
          <div class="sender">Hello world</div>
          <div class="receiver">I'm happy you get back to me</div>
          <div class="sender">Hello world</div>
          <div class="receiver">I'm happy you get back to me</div>
          <div class="sender">Hello world</div>
          <div class="receiver">I'm happy you get back to me</div>
          <div class="sender">Hello world</div>
          <div class="receiver">I'm happy you get back to me</div>
          <div class="sender">Hello world</div>
          <div class="receiver">I'm happy you get back to me</div>
          <div class="sender">Hello world</div>
          <div class="receiver">I'm happy you get back to me</div>
          <div class="sender">
            Hello world I'm happy you get back to me 
            Hello world I'm happy you get back to me 
          </div>
          <div class="receiver">I'm happy you get back to me</div>
          <div class="receiver">
            I'm happy you get back to me I'm happy you get back to me I'm happy you get back to me
          </div>
          <div class="sender">Hello world</div>
          <div class="receiver">I'm happy you get back to me</div>
          <div class="sender">Hello world</div>
          <div class="receiver">I'm happy you get back to me</div>
          <div class="sender">Hello world</div>
          <div class="receiver">I'm happy you get back to me</div>
          <div class="sender">Hello world</div>
          <div class="receiver">I'm happy you get back to me</div>
          <div class="sender">Hello world</div>
          <div class="receiver">I'm happy you get back to me</div>
          <div class="sender">Hello world</div>
          <div class="receiver">I'm happy you get back to me</div>
          <div class="sender">Hello world</div>
          <div class="receiver">I'm happy you get back to me</div>
        </div>

        <form action="" id="chat-form">
          <input type="text">
          <input type="submit" value="send">
        </form>
      </main>
  
      <aside id="right">
      </aside>
    </div>
  </div>
</body>
</html> -->
{% block title %}
  chats
{% endblock %}

{% block main %} 
<div id="profile-info">
  <div id="profile">
    <img src="{% static 'blank-profile-pics.png' %}" alt="blank pics">
    <div id="username">{{ friend_profile.username }}</div>
  </div>

  <button id="burger-button">
    <div id="burger"></div>
  </button>
</div>

<div id="chat-message">
  {% for msg in messages %}
  {% if msg.sender.username == user.username %}
  <div class="sender">{{ msg.text }}
    <span class="msg-sent-time">{{ msg.sent_at|time:"H:i" }}</span>
  </div>
  {% endif %} 
  {% if msg.sender.username == friend_profile.username %}
  <div class="receiver">{{ msg.text }}
    <span class="msg-sent-time">{{ msg.sent_at|time:"H:i" }}</span>
  </div>
  {% endif %} 
  {% endfor %} 
</div>

<form action="{% url 'chat:chat_friend' friend_profile.username %}" id="chat-form" method="post">
  {% csrf_token %} 
  <input type="text" name="msg" id="msg-input">
  <input type="submit" value="send">
</form>

<script>
  // const chat_form = document.querySelector("#chat-form");
  // const input_text = document.querySelector("input[type=text]");
  // console.log(input_text);
  // const submit_bttn = document.querySelector('input[type=submit]');
  // console.log(submit_bttn);
  // submit_bttn.addEventListener('click', () => {
  //   console.log(input_text);
  // });

  $('#chat-form').submit(
      (e) => {
        e.preventDefault();

        $.ajax({
          method: 'POST',
          url: "{% url 'chat:chat_friend' friend_profile.username %}",
          headers: {'X-CSRFToken': $('input[name=csrfmiddlewaretoken]').val()},
          contentType: "application/json",
          data: JSON.stringify(
            {msg: $("#msg-input").val()}
          ),
          success: (res) => {
            $('#msg-input').val('');
            console.log("Message Sent");
          }
        });
      }
    );

</script>
{% endblock %} 