chat/urls.py
from django.urls import path

from . import views


app_name='chat'
urlpatterns = [
    path('', views.chatFriendList, name='home'),
    path('friends', views.acceptedFriends, name='friends'),
    path('follow/request', views.followRequest, name='follow-req'),
    path('<str:friend_username>', views.chatWithFriend, name='chat_friend'),
    path('friend/<str:friend>/add', views.addNewFriends, name='add-friends'),
    path('friend/<str:friend>/accept', views.acceptFriendRequest, name='accept-friend-request'),
    path('friend/<str:friend>/remove', views.removeFriend, name='remove-friend'),
    path('message/unread', views.getNoUnreads, name='unreads'),
    path('friends/no', views.getNoFriends, name='no_friends'),
    path('groups/no', views.getNoGroups, name='no_groups'),
]

konnet/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic.base import RedirectView


from account import views


urlpatterns = [
    path("favivon.ico", RedirectView.as_view(url="blank_profile_pics.png")),
    path('__reload__/', include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
    path('auth/', include('account.urls')),
    path('', include('post.urls')),
]

handler404 = 'account.views.page_not_found'

handler500 = 'account.views.server_error'


# import time
# import threading

# def test():
#     while True:
#         time.sleep(10)
#         print("hello world")
    
# t1 = threading.Thread(target=test)
# t1.start()

post/urls.py
from django.urls import path

from . import views


app_name = 'post'
urlpatterns = [
    path('', views.home, name='home'),
    path('update', views.updatePost, name='update-post'),
    path('profile', views.profile, name='profile'),
    path('profile/<str:user>', views.friend_profile, name= "friend-profile"),
]

post/models.py
from django.db import models
from django.conf import settings

from account.models import Profile


class FilePost(models.Model):
    # post = models.ForeignKey(Post, on_delete=models.CASCADE)
    file = models.FileField(upload_to="upload/posts")
    like = models.ManyToManyField(settings.AUTH_USER_MODEL)

class Post(models.Model):
    poster = models.ForeignKey(Profile, related_name="Poster", on_delete=models.CASCADE)
    text = models.TextField()
    file_post = models.ManyToManyField(FilePost)
    when_posted = models.DateTimeField(auto_now=True)
    like = models.ManyToManyField(Profile, related_name="like")

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

    def __str__(self):
        return self.text[:15]
    

class Comment(models.Model):
    post = models.ForeignKey(Post, blank=True, on_delete=models.CASCADE)
    file_post = models.ForeignKey(FilePost, blank=True, on_delete=models.CASCADE)
    text = models.TextField()
    date_time = models.DateTimeField(auto_now=True)
    like = models.ManyToManyField(Profile)

class Reply(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    text = models.TextField()
    date_time = models.DateTimeField(auto_now=True)
    inner_reply = models.ForeignKey('Reply', on_delete=models.CASCADE)
    like = models.ManyToManyField(settings.AUTH_USER_MODEL)

    class Meta:
        verbose_name = 'Reply'
        verbose_name_plural = 'Replies'

    def __str__(self):
        return self.text[:10]

post/views.py
import json

from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

from account.models import Profile
from .models import Post

@csrf_exempt
@login_required
def home(request):

    posts = Post.objects.all()

    if request.method == 'POST':
        user_profile = Profile.objects.get(username=request.user.username)
        data = json.load(request)

        user_post = data['user_post'].strip()
        
        post = Post.objects.create(poster=user_profile, text=user_post)
        post.save()
        return JsonResponse({'status': 201})
    
    context = {'posts': posts}
    return render(request, 'post/post.html', context)

def updatePost(request):
    posts = Post.objects.all()

    posts = Post.objects.values()
    print(posts)

    context = {
        'posts': posts
    }

    return JsonResponse(context)

def profile(request):
    username = request.user.username

    user_profile = Profile.objects.get(username=username)
    posts = Post.objects.filter(poster=user_profile)
    
    context = {
        'user_profile': user_profile,
        "posts": posts
    }

    return render(request, 'profile/user-profile.html', context)

@login_required
def friend_profile(request, user):
    profile = Profile.objects.get(username=user)
    friend_post = Post.objects.filter(poster=profile)

    context = {
        'profile': profile,
        'friend_post': friend_post
    }

    return render(request, 'profile/user-profile.html', context)

templates/post/post.html
{% extends 'base/base.html' %} 

{% block title %}
Post
{% endblock %}

{% load static %}

{% block custom-style %}
<link rel="stylesheet" href="{% static 'post/new-style.css' %}">

{% endblock %}

{% block main %}
  <form action="#" id="user-post-form">
    <!-- <input type="text"> -->
    {% csrf_token %}
    <div contenteditable role="textbox" id="textbox"></div>
    <input id='post-bttn' type="submit" value="Post">
  </form>
  
  <div id="post-list">
    <div class="post">
      <div class="post-profile">
        <a href="" class="avatar-link">
          <img src="{% static 'blank-profile-pics.png' %}" alt="blank profile pics">
        </a>
        <a href="" class="profile-link">
          <span class="profile-name">David</span>
          <span class="profile-username">@davidjoy</span>
        </a>
        <span>.</span>
        <span>17hrs</span>
      </div>
      <div class="posts">
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit repellendus recusandae explicabo, voluptatem non ipsam minima reprehenderit earum odio debitis porro, deleniti id facilis. Dicta sint enim autem esse cum.
      </div>
      <div class="reactions">
        <span><a href="#">like</a></span>
        <span><a href="#">comment</a></span>
      </div>
    </div>

    <div class="post">
      <div class="post-profile">
        <a href="" class="avatar-link">
          <img src="{% static 'blank-profile-pics.png' %}" alt="blank profile pics">
        </a>
        <a href="" class="profile-link">
          <span class="profile-name">David</span>
          <span class="profile-username">@davidjoy</span>
        </a>
        <span>.</span>
        <span>17hrs</span>
      </div>
      <div class="posts">
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit repellendus recusandae explicabo, voluptatem non ipsam minima reprehenderit earum odio debitis porro, deleniti id facilis. Dicta sint enim autem esse cum.
      </div>
      <div class="reactions">
        <span><a href="#">like</a></span>
        <span><a href="#">comment</a></span>
      </div>
    </div>

    <div class="post">
      <div class="post-profile">
        <a href="" class="avatar-link">
          <img src="{% static 'blank-profile-pics.png' %}" alt="blank profile pics">
        </a>
        <a href="" class="profile-link">
          <span class="profile-name">David</span>
          <span class="profile-username">@davidjoy</span>
        </a>
        <span>.</span>
        <span>17hrs</span>
      </div>
      <div class="posts">
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit repellendus recusandae explicabo, voluptatem non ipsam minima reprehenderit earum odio debitis porro, deleniti id facilis. Dicta sint enim autem esse cum.
      </div>
      <div class="reactions">
        <span><a href="#">like</a></span>
        <span><a href="#">comment</a></span>
      </div>
    </div>

    <div class="post">
      <div class="post-profile">
        <a href="" class="avatar-link">
          <img src="{% static 'blank-profile-pics.png' %}" alt="blank profile pics">
        </a>
        <a href="" class="profile-link">
          <span class="profile-name">David</span>
          <span class="profile-username">@davidjoy</span>
        </a>
        <span>.</span>
        <span>17hrs</span>
      </div>
      <div class="posts">
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit repellendus recusandae explicabo, voluptatem non ipsam minima reprehenderit earum odio debitis porro, deleniti id facilis. Dicta sint enim autem esse cum.
      </div>
      <div class="reactions">
        <span><a href="#">like</a></span>
        <span><a href="#">comment</a></span>
      </div>
    </div>

    <div class="post">
      <div class="post-profile">
        <a href="" class="avatar-link">
          <img src="{% static 'blank-profile-pics.png' %}" alt="blank profile pics">
        </a>
        <a href="" class="profile-link">
          <span class="profile-name">David</span>
          <span class="profile-username">@davidjoy</span>
        </a>
        <span>.</span>
        <span>17hrs</span>
      </div>
      <div class="posts">
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit repellendus recusandae explicabo, voluptatem non ipsam minima reprehenderit earum odio debitis porro, deleniti id facilis. Dicta sint enim autem esse cum.
      </div>
      <div class="reactions">
        <span><a href="#">like</a></span>
        <span><a href="#">comment</a></span>
      </div>
    </div>

    <div class="post">
      <div class="post-profile">
        <a href="" class="avatar-link">
          <img src="{% static 'blank-profile-pics.png' %}" alt="blank profile pics">
        </a>
        <a href="" class="profile-link">
          <span class="profile-name">David</span>
          <span class="profile-username">@davidjoy</span>
        </a>
        <span>.</span>
        <span>17hrs</span>
      </div>
      <div class="posts">
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit repellendus recusandae explicabo, voluptatem non ipsam minima reprehenderit earum odio debitis porro, deleniti id facilis. Dicta sint enim autem esse cum.
      </div>
      <div class="reactions">
        <span><a href="#">like</a></span>
        <span><a href="#">comment</a></span>
      </div>
    </div>

    <div class="post">
      <div class="post-profile">
        <a href="" class="avatar-link">
          <img src="{% static 'blank-profile-pics.png' %}" alt="blank profile pics">
        </a>
        <a href="" class="profile-link">
          <span class="profile-name">David</span>
          <span class="profile-username">@davidjoy</span>
        </a>
        <span>.</span>
        <span>17hrs</span>
      </div>
      <div class="posts">
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit repellendus recusandae explicabo, voluptatem non ipsam minima reprehenderit earum odio debitis porro, deleniti id facilis. Dicta sint enim autem esse cum.
      </div>
      <div class="reactions">
        <span><a href="#">like</a></span>
        <span><a href="#">comment</a></span>
      </div>
    </div>
  </div>
  <script>
    $('#user-post-form').submit(
      (e) => {
        e.preventDefault();

        var CSRF_token = $('input[name=csrfmiddlewaretoken]').val();

        var text_data = document.querySelector('[contenteditable]').innerText

        $.ajax({
          method: 'POST',
          url: "{% url 'post:home' %}",
          headers: {'X-CSRFToken': '{{ CSRF_token }}'},
          contentType: "application/json",
          data: JSON.stringify(
            {user_post: text_data}
            ),
          success: (res) => {
            $('[contenteditable]').html('')
          }
        });
      }
    );
    // const user_post_form = document.querySelector("#user-post-form");
    // user_post_form.addEventListener('submit', (e) => {
    //   e.preventDefault();
    //   const textbox = document.querySelector("#textbox");
    //   let textbox_text = textbox.innerText;
    //   if (textbox_text) {
    //     console.log(textbox_text);
    //     textbox.innerText = '';
    //   }
    //   $.ajax({
    //     url: "{% url 'post:home' %}",
    //     method: 'post',
    //     success: (data, status) => {
    //       {post: textbox}
    //       console.log(data, status);
    //     }
    //   });
    // });
  </script>
{% endblock %}